# Generated by Django 6.0.5 on 2026-05-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
